In [84]:
import os
import pandas as pd

In [97]:
file = os.path.join("output/ranking_2019_per.csv")

In [99]:
z_score = pd.read_csv(file)
#z_score.head(30)

In [100]:
file_2 = os.path.join("resources/fantasy_rankings.csv")

In [101]:
fantasy = pd.read_csv(file_2)
#fantasy

In [102]:
z_score["Name"] = z_score["Name"].astype('string')

In [103]:
fantasy["Player"] = fantasy["Player"].astype('string')

In [104]:
from unidecode import unidecode

In [105]:
z_score["Name"] = z_score["Name"].apply(unidecode)

In [106]:
try:
    fantasy["Player"] = fantasy["Player"].apply(unidecode)
except:
    pass

In [107]:
fantasy = fantasy[["Rank", "Player"]]

In [108]:
merged = pd.merge(fantasy, z_score, left_on="Player", right_on="Name", how="inner")
merged

,Rank_x,Player,Rank_y,Name,Pos,Z Total
0,1.0,James Harden,1,James Harden,SG,15.284431
1,2.0,Anthony Davis,2,Anthony Davis,PF,14.283842
2,3.0,Luka Doncic,15,Luka Doncic,PG,8.951041
3,4.0,Karl-Anthony Towns,4,Karl-Anthony Towns,C,11.679675
4,5.0,Giannis Antetokounmpo,5,Giannis Antetokounmpo,PF,11.337085
...,...,...,...,...,...,...
264,313.0,Torrey Craig,277,Torrey Craig,SF,-1.269870
265,314.0,Cameron Payne,82,Cameron Payne,SG,3.939623
266,315.0,Jevon Carter,233,Jevon Carter,PG,-0.270648
267,316.0,Trey Burke,294,Trey Burke,PG,-1.646235
268,317.0,E'Twaun Moore,301,E'Twaun Moore,SG,-1.842797

In [109]:
rename = merged.rename(columns={
    'Rank_x': "Fantasy Ranking",
    'Rank_y': "Z-Score Ranking",
})
rename

,Fantasy Ranking,Player,Z-Score Ranking,Name,Pos,Z Total
0,1.0,James Harden,1,James Harden,SG,15.284431
1,2.0,Anthony Davis,2,Anthony Davis,PF,14.283842
2,3.0,Luka Doncic,15,Luka Doncic,PG,8.951041
3,4.0,Karl-Anthony Towns,4,Karl-Anthony Towns,C,11.679675
4,5.0,Giannis Antetokounmpo,5,Giannis Antetokounmpo,PF,11.337085
...,...,...,...,...,...,...
264,313.0,Torrey Craig,277,Torrey Craig,SF,-1.269870
265,314.0,Cameron Payne,82,Cameron Payne,SG,3.939623
266,315.0,Jevon Carter,233,Jevon Carter,PG,-0.270648
267,316.0,Trey Burke,294,Trey Burke,PG,-1.646235
268,317.0,E'Twaun Moore,301,E'Twaun Moore,SG,-1.842797

In [111]:
final_df = rename[["Player", "Pos", "Fantasy Ranking", "Z-Score Ranking", 'Z Total']]
final_df['Difference'] = final_df["Fantasy Ranking"] - final_df["Z-Score Ranking"]
final_df.to_csv("output/delta_fantasy_2019_per.csv", index=False)